### ISSUE TITLE
rf2depth: ValueError: could not broadcast input array from shape (92,3) into shape (3,4)

### ISSUE THREAD

**Issue by ShihChi90** [xumi1993/seispy#86]
**Describe the bug**
I was running the usual workflow doing time to depth migration using rf2depth module, but ran in to arror somewhere reading depmodel. I was using same vmod as I was in seispy 1.3.4, but after updating to 1.3.5 it show this error. I downgrade my package and it worked again.

**Expected behavior**
should run a time migration and output an npy file

**Error raised**
File "/home/scshao/.conda/envs/seispy/lib/python3.11/site-packages/seispy/core/depmodel.py", line 51, in _search_vel_file
    model[:3, :] = raw_model[:, :]
    ~~~~^^^
ValueError: could not broadcast input array from shape (92,3) into shape (3,4)
![image](https://github.com/xumi1993/seispy/assets/95597521/0c34de17-1474-4aa3-9ad7-f0496009fdd7)


**Platform (please complete the following information):**
Linux
seispy 1.3.5

**Additional context**
Appreciated developer's work, very good project!

**Comment by xumi1993** [comment]
Thanks for reporting this. I will check it ASAP.

**Comment by xumi1993** [comment]
I have fixed this bug on commit 4b00da9. You can update Seispy to dev branch to solve this problem.

**Comment by ShihChi90** [comment]
another error occured after fixing depmodel
in core/pertmod.py
AttributeError: 'DepModel' object has no attribute 'depthsraw'. Did you mean: 'depths'?
after renaming the attributes (depthsraw -> depths, vpraw/vsraw -> vp/vs) it looks to work fine.
![image](https://github.com/xumi1993/seispy/assets/95597521/1f8e511e-aedd-41c0-ada8-0ea94aa789b3)

**Comment by xumi1993** [comment]
I have fixed it. Pls update to `dev` branch and have a try. Thanks.
